# Generated by Django 4.0 on 2024-01-30 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_code_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время последней отправки кода'),
        ),
    ]
