# Generated by Django 4.0 on 2024-01-17 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passengercars',
            options={'verbose_name': 'Добавить объявление', 'verbose_name_plural': 'Добавить объявление'},
        ),
        migrations.RemoveField(
            model_name='passengercars',
            name='car_year',
        ),
        migrations.RemoveField(
            model_name='passengercars',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='passengercars',
            name='mileage',
        ),
        migrations.AddField(
            model_name='passengercars',
            name='engine',
            field=models.CharField(choices=[('БЕНЗИН', 'Бензин'), ('Дизель', 'Дизель')], default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengercars',
            name='manufacturing_year',
            field=models.IntegerField(choices=[(1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=3, validators=[django.core.validators.MinValueValidator(1960, 'Выберите даьу'), django.core.validators.MaxValueValidator(2024, 'выуаыка')], verbose_name='God'),
            preserve_default=False,
        ),
    ]
