# Generated by Django 4.0 on 2024-01-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengercars',
            name='generation',
        ),
    ]
