# Generated by Django 4.0 on 2024-01-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_passengercars_drive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengercars',
            name='drive',
            field=models.CharField(choices=[('Задний', 'Задний'), ('Передний', 'Передный')], max_length=50, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='passengercars',
            name='engine',
            field=models.CharField(choices=[('БЕНЗИН', 'Бензин'), ('Дизель', 'Дизель')], max_length=50, verbose_name='Двигатель'),
        ),
    ]
