# Generated by Django 4.0 on 2024-01-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_passengercars_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengercars',
            name='video_youtube',
        ),
    ]
