# Generated by Django 4.0 on 2024-01-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_passengercars_drive_alter_passengercars_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengercars',
            name='body',
            field=models.CharField(choices=[('Седан', 'Cедан'), ('Универсал', 'Универсал'), ('Хетчбэк', 'Хетчбэк')], default=3, max_length=50, verbose_name='Тип кузова'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengercars',
            name='gearbox',
            field=models.CharField(choices=[('Механика', 'Механика'), ('Автомат', 'Автомат')], default=3, max_length=50, verbose_name='Каробка передач'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengercars',
            name='generation',
            field=models.ImageField(default=1, upload_to='mediad/', verbose_name='Поколение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengercars',
            name='images',
            field=models.ImageField(default=1, upload_to='medida/', verbose_name='Фотографии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengercars',
            name='modification',
            field=models.IntegerField(choices=[('Слева', 'Слева'), ('Справа', 'Справа')], default=1, verbose_name='Руль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengercars',
            name='video_youtube',
            field=models.URLField(default=1, help_text='Введите URL-ссылку на YouTube видео'),
            preserve_default=False,
        ),
    ]
